### ISSUE TITLE
StatusEverywhere causes profile pictures to display in the wrong (too low) resolution.

### ISSUE THREAD

**Issue by ItsCubeTime** [Strencher/BetterDiscordStuff#119] opened 2021-12-27 10:01 UTC
With StatusEverywhere enabled (note the php to the left) :
![image](https://user-images.githubusercontent.com/20190653/147460425-47083fc8-9701-4d57-a1bd-e24983477bd9.png)

Without StatusEverywhere (much sharper pfp, again, only the one to the left is relevant) :
![image](https://user-images.githubusercontent.com/20190653/147460549-12cbf4de-4768-4623-b6d6-1e34fe208ef5.png)

**Comment by SmolAlli** [comment] 2021-12-27 11:49
Duplicate of #88

**Closed** 2022-02-11 08:05 UTC
