### ISSUE TITLE
profile pictures💀 

### ISSUE THREAD

**Issue by xdjoee** [Strencher/BetterDiscordStuff#159] opened 2022-03-09 18:52 UTC
![xxxxx](https://user-images.githubusercontent.com/69331937/157511203-76633cf7-2357-491e-a6f1-d8ca461e7f3a.png)

**Comment by TheLostChallenger** [comment] 2022-03-09 19:06
Experiencing the same thing

**Comment by TheLostChallenger** [comment] 2022-03-09 19:07
Wait, you have to put this line of code in it

 .avatar-2e8lTP:before {display: none;}

**Comment by HypedDomi** [comment] 2022-03-09 19:21
The Problem is already reported in #156

**Comment by Strencher** [comment] 2022-03-09 21:22
duplicate of #158

**Closed by Strencher** 2022-03-09 21:22 UTC

**Comment by notnicknamed** [comment] 2024-03-29 01:15
Hello. I would like to report I am having a similar problem.
