### ISSUE TITLE
[BUG] Platform Inidcator detailed text glithes when user logs off

### ISSUE THREAD

**Issue by PitchBlackNights** [Strencher/BetterDiscordStuff#319] opened 2022-11-16 23:07 UTC
I came across this bug entirely by accident

### How to reproduce
Hover over the platform indicator of a user and wait till the detailed text is shown
Then have the user log off (or go invisible) while still hovering over the indicator
Now the detailed text will stay there on your screen until you restart discord

The bug will persist across servers, settings, minifying the window, or collapsing the window to the program tray and then reopening

I would attach an image, but I reloaded discord while trying to fix the bug, and it disappeared. I currently have no way of trying to reproduce rn, but I will upload an image once I do.

**Comment by fowlis** [comment] 2022-11-16 23:36
Duplicate of https://github.com/Strencher/BetterDiscordStuff/issues/298

**Closed** 2022-11-16 23:53 UTC
Labels: duplicate
