### ISSUE TITLE
Profile Pictures are not in the right spot

### ISSUE THREAD

**Issue by Aaron987BTW** [Strencher/BetterDiscordStuff#158] opened 2022-03-09 16:33 UTC
When somebody sends in a chat in a sever or sends a dm to me, the profile picture is always placed under where it should be.
![grafik](https://user-images.githubusercontent.com/89487362/157486359-b8e137fe-b3bc-4ef1-bd69-71bb04e93ce3.png)

Does anybody know how to fix that?

**Comment by Aaron987BTW** [comment] 2022-03-09 16:36
![grafik](https://user-images.githubusercontent.com/89487362/157487129-0482bf83-9a7c-49a4-a060-8208f4b5b543.png)

**Comment by Aaron987BTW** [comment] 2022-03-09 16:37
btw this is status everywhere

**Comment by HypedDomi** [comment] 2022-03-09 17:42
You can use this as temp fix
```css
.avatar-2e8lTP:before {display: none;}
```
The Problem is already reported in #156

**Comment by WhiteEnderman14** [comment] 2022-03-09 19:03
> You can use this as temp fix
> 
> ```css
> .avatar-2e8lTP:before {display: none;}
> ```
> 
> The Problem is already reported in #156

where I should put it?

**Comment by Aaron987BTW** [comment] 2022-03-09 19:08
> You can use this as temp fix
> 
> ```css
> .avatar-2e8lTP:before {display: none;}
> ```
> 
> The Problem is already reported in #156

Thank you for your answer.

**Comment by TheLostChallenger** [comment] 2022-03-09 19:15
wait, where do we put that line of code?

**Comment by JaehaerysNL** [comment] 2022-03-09 19:33
Thank you HypedDomi, that resolved it for now.

For the people that still don't understand, use the following reproduction steps:

01) Install/Enable BD (If you uninstalled or reinstalled for thinking it was a bug for instance)
02) Enable StatusEverywhere (if you disabled it bc of the bug)
03) Enable Custom CSS
04) Head toward the Custom CSS Editor under BD Settings.
05) Write `.avatar-2e8lTP:before {display: none;}` on the first line of the Custom CSS Editor
06) Save changes.
07) Profit!

**Comment by ThalusA** [comment] 2022-03-22 12:43
@Strencher Hey, are you planning on fixing it?

**Comment by HypedDomi** [comment] 2022-05-16 22:39
@Strencher You can close this

**Closed** 2022-08-15 02:37 UTC
