### ISSUE TITLE
APlatformIndicators TypeError

### ISSUE THREAD

**Issue by FarikLoL** [Strencher/BetterDiscordStuff#411] opened 2024-06-29 02:34 UTC
web.d25f20b917981dc9b949.js:12 [BetterDiscord] [Patcher] Could not fire after callback of type for APlatformIndicators TypeError: Cannot read properties of undefined (reading 'bot')
    at Object.eval [as callback] (APlatformIndicators.plugin.js:595:68)
    at renderer.js:5:22972
    at aA (web.d25f20b917981dc9b949.js:12:990088)
    at oh (web.d25f20b917981dc9b949.js:12:1001987)
    at l (web.d25f20b917981dc9b949.js:12:1046221)
    at sk (web.d25f20b917981dc9b949.js:12:1028319)
    at web.d25f20b917981dc9b949.js:12:1028185
    at sG (web.d25f20b917981dc9b949.js:12:1028193)
    at sO (web.d25f20b917981dc9b949.js:12:1023230)
    at N (web.d25f20b917981dc9b949.js:12:1221987)
    at L (web.d25f20b917981dc9b949.js:12:1222517)
    at T.C.<computed> (web.d25f20b917981dc9b949.js:1:640606)
    at D (web.d25f20b917981dc9b949.js:1:640371)
    at MessagePort.b (web.d25f20b917981dc9b949.js:1:640430)

**Comment by domi-btnr** [comment] 2024-06-29 20:54
I can't reproduce the Issue.
https://github.com/Strencher/BetterDiscordStuff/assets/50876016/fc3b173c-ee66-40e1-871b-d69fb8ca2525

Could you try the following:
1. Delete `APlatformIndicators.plugin.js` and `APlatformIndicators.config.json` from your Plugins Folder
2. Fully close Discord (Close via Tray Icon)
3. Redownload PlatformIndicators from [here](https://betterdiscord.app/plugin/PlatformIndicators)
4. Move the Plugin into your Plugins Folder
5. Start Discord and see if the Issue is still there

For now, I'd close the Issue. If you still have the issue after completely reinstalling it, then I'll reopen it

**Closed by domi-btnr** 2024-06-29 20:54 UTC
