### ISSUE TITLE
ShowSessions - Could not be constructed ERROR

### ISSUE THREAD

**Issue by DS-GitHub** [Strencher/BetterDiscordStuff#63] opened 2021-07-24 03:10 UTC
![image](https://user-images.githubusercontent.com/37930090/126855780-6e158e17-ecb6-4018-bb8b-2e793b9e1b21.png)
The plugin couldn't be loaded in my BD (Discord Canary)

**Comment by piotr25691** [comment] 2021-07-24 07:19
the same error applies to UserDetails, please fix.

**Comment by Strencher** [comment] 2021-07-24 09:40
Redownload the files. I pushed a fix to <https://github.com/Strencher/BetterDiscordStuff/tree/master>

**Comment by NotOfficer** [comment] 2021-07-24 10:08
Still not working, same error.

**Comment by Strencher** [comment] 2021-07-24 10:09
Reload your client, there's a little cache issue.

**Comment by NotOfficer** [comment] 2021-07-24 10:17
Thanks, that was the issue.

**Comment by xGlobalShock** [comment] 2021-07-24 20:45
![Screenshot_1](https://user-images.githubusercontent.com/83690739/126880710-b4ff6696-cb78-40ea-93d2-5f7389667880.png)
I have downloaded the file and reloaded discord multiple times, didn't work.

**Comment by Strencher** [comment] 2021-07-24 20:46
these are multiple files. Get them from <https://github.com/Strencher/BetterDiscordStuff/tree/master>

**Comment by Iinksafe** [comment] 2021-07-25 09:59
Can reproduce.

**Comment by marcpinet** [comment] 2021-07-25 13:46
![image](https://user-images.githubusercontent.com/52708150/126901395-14e6b2c4-c716-4013-a784-201345c2795d.png)

**Comment by Strencher** [comment] 2021-07-25 13:57
Redownload them from the [BetterDiscord Site](https://betterdiscord.app/plugins) and make sure you reload your client.

**Comment by marcpinet** [comment] 2021-07-25 13:58
> Redownload them from the [BetterDiscord Site](https://betterdiscord.app/plugins) and make sure you reload your client.

already did it, doesn't solve the issue

**Comment by Strencher** [comment] 2021-07-25 13:59
Did you reload your client with `Ctrl + R` ?

**Comment by marcpinet** [comment] 2021-07-25 13:59
> Did you reload your client with `Ctrl + R` ?

yeah

**Comment by Strencher** [comment] 2021-07-25 14:00
Hmm, that seems to fix issue for almost everyone that had the startup issue. Can you straight up delete the files reload your client (Check if any other errors occur) and download them again?

**Comment by Strencher** [comment] 2021-07-25 14:00
Because the files just need to be replaced in your plugins folder.

**Closed** 2021-07-31 14:19 UTC
