### ISSUE TITLE
[InvisibleTyping] Typing still shows up

### ISSUE THREAD

**Issue by Breetlez** [Strencher/BetterDiscordStuff#255] opened 2022-08-06 08:36 UTC
The InvisibleTyping error message that shows up recently got fixed but I test it after the 1.2.2v I can see myself typing in channels not hidden. Can anyone confirm this too?

Ptb 140355 (cd30e81)
BetterDiscord 1.5.3-Hotfix2
Host 1.0.1016 Windows 10 64-Bit (10.0.19044)

**Comment by EMREOYUN** [comment] 2022-08-07 09:10
Duplicate #245

**Comment by HypedDomi** [comment] 2022-08-15 02:07
Cant confirm. Works fine with the latest Version

**Comment by HypedDomi** [comment] 2022-09-02 19:02
@Breetlez Do you still have this issue or can i close this?

**Comment by bossanovaorca** [comment] 2022-09-09 06:06
@HypedDomi the issue is present on Discord canary for me

**Comment by HypedDomi** [comment] 2022-09-09 07:38
Do you have the latest Version of ZeresPluginLibrary (v2.0.5) and InvisibleTyping (v1.2.2)?

**Comment by bossanovaorca** [comment] 2022-09-09 07:50
yes I am using ZeresPluginLibrary v2.0.5 and InvisibleTyping v1.2.2

**Comment by HypedDomi** [comment] 2022-09-09 07:54
Do you have this Keyboard Icon in the chat bar?
<img width="91" alt="image" src="https://user-images.githubusercontent.com/50876016/189300503-d0ebae6c-0e4c-4d85-84bf-9510ebd0d006.png">

**Comment by bossanovaorca** [comment] 2022-09-09 09:31
oh I see now, the option to enable typing in all channels was on by default in the settings menu. you can close this as resolved!

**Closed** 2022-09-09 09:54 UTC
