### ISSUE TITLE
[CRASH] [APlatformIndicators] Crash when Discord start

### ISSUE THREAD

**Issue by AZERTY442005** [Strencher/BetterDiscordStuff#404] opened 2024-04-16 18:28 UTC
When Discord starts, APlatformIndicators seems to crash and crash Discord
![image](https://github.com/Strencher/BetterDiscordStuff/assets/73392042/8aaaddac-1833-4ef1-b1b8-28e949db849c)
When I disable APlatformIndicators, Discord is working again.
Thats the only thing I have to help sorry

**Comment by Technetium1** [comment] 2024-04-16 18:34
Manually download the latest version from https://raw.githubusercontent.com/Strencher/BetterDiscordStuff/master/PlatformIndicators/APlatformIndicators.plugin.js
This is likely a duplicate of https://github.com/Strencher/BetterDiscordStuff/issues/403 and https://github.com/Strencher/BetterDiscordStuff/issues/398
If it continues, use CTRL+SHIFT+I to open developer tools, and copy the errors from `console`.

**Closed** 2024-04-19 11:21 UTC
