### ISSUE TITLE
Plugin makes Discord crash, fix it

### ISSUE THREAD

**Issue by AxesOne1** [Strencher/BetterDiscordStuff#381] opened 2023-12-09 14:17 UTC
I think it's my favorite Discord plugin but since yesterday it started to make my Discord crash, we need an update to fix this problem and make it work again

**Comment by AZERTY442005** [comment] 2023-12-10 09:40
which one ?

**Comment by Gregoryn14** [comment] 2023-12-10 14:00
> which one ? which plugin ?

PlatformIndicators

**Comment by AZERTY442005** [comment] 2023-12-10 15:05
> > > which one ? which plugin ?
> > 
> > 
> > PlatformIndicators
> 
> PlatformIndicators also make my discord crash, so i had to uninstall and not use it until it is fix

Me too

**Comment by appcapsergen** [comment] 2023-12-11 11:56
Same here

**Comment by DGVaniX** [comment] 2023-12-12 11:58
Same here, every time I open discord or turn on the plugin it crashes

**Comment by appcapsergen** [comment] 2023-12-13 09:29
@fowlis He may already know about the issue, but it's important to let him know that others are also affected. This might make it a higher priority to fix, so people don't stop using the plugin altogether.
But I guess sorry for mentioning I'm having the same problem?

**Comment by fowlis** [comment] 2023-12-13 10:17
@appcapsergen while yes, it is important to know how many users are experiencing the same problem, not a lot of them are able to share this info in the most constructive way is where I find issue. 
From what I've seen from a lot of the end-users in the client modding scene, I see a prominent instant-gratification mindset where most are unwilling to put any effort into troubleshooting their problems; for example the author of this very post didn't even bother to find out what plugin(s) was making them crash, or provide any useful error messages that would help Strencher find what is broken with the afflicted plugin(s) and make fixing them easier - they just wanted it to be fixed immediately.
It took another user commenting on this post to even mention which plugin was at fault for the issue the author was experiencing, and since then nobody here has shared any more useful information other than "same", which ultimately leads nowhere.

Your point in that it 'prioritizes" the plugin to be fixed while largely true, does not wholly apply since most development in this scene is for the most part a hobby for the devs, they have lives outside of making and fixing plugins so that some people on the internet can enjoy their work for a limited amount of time until stuff breaks again - which then repeats the cycle of people not providing anything constructive when there is an issue, rather just wanting it fixed ASAP without providing any useful information on what their issue is 90% of the time.

**Comment by appcapsergen** [comment] 2023-12-13 12:27
@fowlis I understand your frustration with users not providing detailed feedback in the modding scene. However, it's important to remember that not everyone has the technical knowledge to give detailed error reports. Like many, I've experienced crashes without error messages, limiting my ability to contribute more than a basic problem report (or; "same").

It's also not fair to assume all users demand immediate fixes. Comments like "same" might not offer much detail, but they do indicate the prevalence of an issue, which is helpful.

Regarding issue prioritization, my suggestion is about organizing workflow for when the developer has time, not to impinge on his personal time. It's about understanding the scale of a problem and addressing issues, that affect more users, first.

**Comment by Nova1ite** [comment] 2023-12-14 21:56
> @fowlis I understand your frustration with users not providing detailed feedback in the modding scene. However, it's important to remember that not everyone has the technical knowledge to give detailed error reports. Like many, I've experienced crashes without error messages, limiting my ability to contribute more than a basic problem report (or; "same").
> 
> It's also not fair to assume all users demand immediate fixes. Comments like "same" might not offer much detail, but they do indicate the prevalence of an issue, which is helpful.
> 
> Regarding issue prioritization, my suggestion is about organizing workflow for when the developer has time, not to impinge on his personal time. It's about understanding the scale of a problem and addressing issues, that affect more users, first.

I think the problem is that this repeated topic has been created multiple times when Strencher knows that this is an issue already.  Someone already posted the same exact issue like more than a week ago and I provided the error log and more open issue topics are being made after. There has been a temporary fix in the topic I created in the BD discord support channel, so if users are willing to use those instead for the short moment, it's up to them. (https://ptb.discord.com/channels/86004744966914048/1181726539231019048) (I used one of them, its working fine for me now temporarily until an official fix)

**Comment by DGVaniX** [comment] 2023-12-14 22:34
> @appcapsergen while yes, it is important to know how many users are experiencing the same problem, not a lot of them are able to share this info in the most constructive way is where I find issue. From what I've seen from a lot of the end-users in the client modding scene, I see a prominent instant-gratification mindset where most are unwilling to put any effort into troubleshooting their problems; for example the author of this very post didn't even bother to find out what plugin(s) was making them crash, or provide any useful error messages that would help Strencher find what is broken with the afflicted plugin(s) and make fixing them easier - they just wanted it to be fixed immediately. It took another user commenting on this post to even mention which plugin was at fault for the issue the author was experiencing, and since then nobody here has shared any more useful information other than "same", which ultimately leads nowhere.
> 
> Your point in that it 'prioritizes" the plugin to be fixed while largely true, does not wholly apply since most development in this scene is for the most part a hobby for the devs, they have lives outside of making and fixing plugins so that some people on the internet can enjoy their work for a limited amount of time until stuff breaks again - which then repeats the cycle of people not providing anything constructive when there is an issue, rather just wanting it fixed ASAP without providing any useful information on what their issue is 90% of the time.

As a developer myself, I understand the technical aspects, but I don't have much knowledge about Discord or Better Discord. I hadn't encountered that crash screen on Discord before the last update. Additionally, there are no clear console logs or debug logs, especially for people like me who aren't familiar with the technicalities of Discord and Better Discord.

I use Better Discord, and I love the plugin, but it crashes at startup with no other information. Initially, I didn't know who developed the plugin, but after doing my due diligence, I found this GitHub repository. I checked to see if there was a post addressing the issue with the developer acknowledging it or any announcements, but there was nothing. I came across this post with not many replies, but since I really like the plugin, I wanted to add my 'same here' to contribute as a metric for how many people are experiencing the issue and bump up this problem.

If asked for logs or further information, and given instructions on how to gather them, I would have happily provided whatever is necessary to help fix the issue.

**Comment by Nova1ite** [comment] 2023-12-14 23:15
@DGVaniX I'll give a somewhat official response from Stern
You could use the temporary fix someone made in the support channel if you still want to use it
![image](https://github.com/Strencher/BetterDiscordStuff/assets/115776661/3951e141-e595-4a56-8b41-fb462a340ce9)

**Comment by TheShizuka** [comment] 2023-12-18 08:54
> @DGVaniX I'll give a somewhat official response from Stern You could use the temporary fix someone made in the support channel if you still want to use it ![image](https://private-user-images.githubusercontent.com/115776661/290680733-3951e141-e595-4a56-8b41-fb462a340ce9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4ODk4OTUsIm5iZiI6MTcwMjg4OTU5NSwicGF0aCI6Ii8xMTU3NzY2NjEvMjkwNjgwNzMzLTM5NTFlMTQxLWU1OTUtNGE1Ni04YjQxLWZiNDYyYTM0MGNlOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOFQwODUzMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YzcyODg5YzYyNmFhOTQ1Nzc3YjNhMjNiYjY1MmRhMmRlMzE2NTVmMTc0NTA2ZWQ1ZDM0M2M2NjY0NDg4YjVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0bGCKBY8QA11jbg1GqOROE7oXxa-oRcGzl93rJtBwbc)


i dont find the temporary fix on the sipport channel can someone guide me pls

**Comment by appcapsergen** [comment] 2023-12-19 11:33
> > @fowlis I understand your frustration with users not providing detailed feedback in the modding scene. However, it's important to remember that not everyone has the technical knowledge to give detailed error reports. Like many, I've experienced crashes without error messages, limiting my ability to contribute more than a basic problem report (or; "same").
> > It's also not fair to assume all users demand immediate fixes. Comments like "same" might not offer much detail, but they do indicate the prevalence of an issue, which is helpful.
> > Regarding issue prioritization, my suggestion is about organizing workflow for when the developer has time, not to impinge on his personal time. It's about understanding the scale of a problem and addressing issues, that affect more users, first.
> 
> I think the problem is that this repeated topic has been created multiple times when Strencher knows that this is an issue already. Someone already posted the same exact issue like more than a week ago and I provided the error log and more open issue topics are being made after. There has been a temporary fix in the topic I created in the BD discord support channel, so if users are willing to use those instead for the short moment, it's up to them. (https://ptb.discord.com/channels/86004744966914048/1181726539231019048) (I used one of them, its working fine for me now temporarily until an official fix)
> 
> ![image](https://private-user-images.githubusercontent.com/115776661/290667826-83f7302b-2432-49b1-aeb5-1cb1e0fb5219.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5ODU4MzcsIm5iZiI6MTcwMjk4NTUzNywicGF0aCI6Ii8xMTU3NzY2NjEvMjkwNjY3ODI2LTgzZjczMDJiLTI0MzItNDliMS1hZWI1LTFjYjFlMGZiNTIxOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOVQxMTMyMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZGNkODBkOTQ1ZTczNThmMTIwMDM4NjY2NGY2YmY2M2NiMGRhYzIwZmFlNDExNDdiNGFjMjBkZWJjMzk2ZDA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GoJ_2JLhO5PJ0szkMVsp38CVJrfOD_yc8cG0a_kycLs)

If that's the case, they could've sent a link to the other issue saying there's already a more detailed issue for it :P

**Comment by Strencher** [comment] 2023-12-22 09:32
I have pushed a fix (https://github.com/Strencher/BetterDiscordStuff/commit/5045c654c89325a91552811bee87ab608e28faeb), it should show up as soon as it gets approved by BD reviewers.

**Closed by Strencher** 2023-12-22 09:32 UTC
