### ISSUE TITLE
PlatformIndicators crashing discord

### ISSUE THREAD

**Issue by Dethkiller15** [Strencher/BetterDiscordStuff#287] opened 2022-09-11 21:23 UTC
No idea what the issue could be but as soon as I attempted to use PlatformIndicators it crashed discord.

to double check that it was ONLY platform indicators that was doing it I removed all but BDFBD from my plugins folder.

Crashed as soon as I enabled platform indicators and tried to go to look into another server. Then it kept crashing upon launch or reload until I deleted PlatformIndicators from my plugins folder.

**Comment by HypedDomi** [comment] 2022-09-11 21:33
Could be a duplicate of #277
Can you send some Errors? (CTRL SHIFT I --> Console and Screenshot big red Errors)

**Comment by Dethkiller15** [comment] 2022-09-11 22:02
To further test if that is indeed the bug I went in and set a private server as the one I would be in when enabling the plugin.

These are the errors I got after viewing a more public server.
![image](https://user-images.githubusercontent.com/49108931/189550667-a96d0d1d-f3bc-4a46-8664-434c78cd02fe.png)

**Closed** 2022-09-13 16:01 UTC
Labels: bug, duplicate
