### ISSUE TITLE
PronounDB broken on newest Updates

### ISSUE THREAD

**Issue by Masono03** [Strencher/BetterDiscordStuff#240] opened 2022-08-03 11:37 UTC
As many other plugins now died on the new updates of discord. Cant be constructed. 

Canary 139699 (bdc9502)
BetterDiscord 1.5.3-Hotfix2
Host 1.0.48 Windows 10 64-Bit (10.0.19044)

**Comment by HypedDomi** [comment] 2022-08-15 02:19
Duplicate of #232

**Closed by HypedDomi** 2022-08-15 02:19 UTC
