### ISSUE TITLE
can't change my status or click on it (idle,DND,etc.)

### ISSUE THREAD

**Issue by md3ja** [Strencher/BetterDiscordStuff#108] opened 2021-11-02 00:04 UTC

**Comment by SmolAlli** [comment] 2021-11-02 00:05
Can you please give some or ANY information about what the problem is?
E.g. what version of Discord and BetterDiscord you're on, what plugin(s) you have on and are causing this, etc etc.
Nobody can help unless you give more information.

**Comment by bbeenn1** [comment] 2021-11-02 08:15
I am having this same issue.
Cannot click on user avatar to bring up the status menu modal/dialog to change status at all, it simply does not open.

**Plugin Version**
StatusEverywhere v2.1.1

**Screenshots**
This is the dialog being talked about
![image](https://user-images.githubusercontent.com/5580320/139809849-4a15272a-7f31-4baa-ae87-2cd2fde2bd32.png)

**Discord Version**
Stable 103255 (ae3387d)
BetterDiscord 1.2.4
Host 1.0.9003 Windows 10 64-Bit (10.0.22000)

**Comment by Rexvivor** [comment] 2021-11-02 11:18
same

**Comment by Strencher** [comment] 2021-11-02 16:36
This issue was fixed in https://github.com/Strencher/BetterDiscordStuff/commit/f40c9a1d0ca99d267f91da02737cfe627d745837

**Closed** 2021-11-02 16:36 UTC
Labels: bug
